syntax on
set number

" Turn off expanding tabs for makefiles
autocmd FileType make setlocal noexpandtab
" Most file types use two spaces for tab
autocmd FileType * set tabstop=2|set shiftwidth=2|set noexpandtab
" For Python use four spaces for tab
autocmd FileType python set tabstop=4|set shiftwidth=4|set expandtab

call plug#begin()
Plug 'ludovicchabant/vim-gutentags'
Plug 'skywind3000/gutentags_plus'
Plug 'tpope/vim-fugitive'
call plug#end()

" enable gtags module
let g:gutentags_modules = ['ctags', 'gtags_cscope']

" generate datebases in my cache directory, prevent gtags files polluting my
" project
let g:gutentags_cache_dir = expand('~/.cache/tags')

" change focus to quickfix window after search (optional).
let g:gutentags_plus_switch = 1

" set statusline+=%{gutentags#statusline()}
